### ISSUE TITLE
really old messages crash the client

### ISSUE THREAD

**Issue by intexisty** [SeanOMik/atlas-discord-client#12]
when loading a message with "04/17/2020" the client promptly crashes
| commit | 5ece992298e3f61eacfa7635dad10ec7a5b7d68e |
|---|---|
| os | windows x86_64 |
| compiler | MSVC |
| build-system | ninja |
| ide | CLion |
![image](https://user-images.githubusercontent.com/30681593/82386542-4e22d200-99fa-11ea-8c97-69d1ece6579c.png)

**Comment by SeanOMik** [comment]
Should be fixed in this [commit](https://github.com/SeanOMik/atlas-discord-client/commit/f963ea1c191f8cac2010f0f6ee331877878c7a56). If it isn't, reopen the issue.
