### ISSUE TITLE
Feature Request: Better timestamps

### ISSUE THREAD

**Issue by intexisty** [SeanOMik/atlas-discord-client#7]
# About
I would like properly formatted timestamps in messages

# Implementation
![image](https://user-images.githubusercontent.com/30681593/82253671-0e36ee80-9917-11ea-875f-2db4c8f4b568.png)

**Comment by SeanOMik** [comment]
It was finished a commit earlier, but this [commit refines it](https://github.com/SeanOMik/atlas-discord-client/commit/2754cc02cd0018c2bfeb3a0b365f6a37f6c78d8c)
